use  CourierManagementSystem
-- task 3
--14. Find the total number of couriers handled by each employee.  
SELECT e.Name AS EmployeeName, COUNT(p.PaymentID) AS TotalCouriers
FROM Employee AS e
LEFT JOIN Payment AS p ON e.EmployeeID = p.CourierID
GROUP BY e.Name
HAVING COUNT(p.PaymentID) > 0;


--15. Calculate the total revenue generated by each location  
select LocationID, SUM(Amount) as TotalRevenue
from Payment
group by LocationID


--16. Find the total number of couriers delivered to each location.  
--SELECT L.LocationName, COUNT(C.CourierID) AS DeliveredCouriers
--FROM Location L
--JOIN Courier C ON L.LocationID = C.LocationID
--WHERE C.Status = 'Delivered'
--GROUP BY L.LocationName;

SELECT COUNT(CourierID) AS TotalDeliveredCouriers
FROM Courier
WHERE Status = 'Delivered';



alter table Courier
add LocationID int;

alter table Courier
add constraint FK_Courier_Location
foreign key (LocationID) references Location(LocationID);


--17. Find the courier with the highest average delivery time: 
SELECT TOP 1 CourierID, AVG(DATEDIFF(day, DeliveryDate, GETDATE())) AS AverageDeliveryTime
FROM Courier
WHERE Status = 'Delivered'
GROUP BY CourierID
ORDER BY AverageDeliveryTime DESC;

--18  Find Locations with Total Payments Less Than a Certain Amount  
select L.LocationName, sum(P.Amount) as TotalPayment
from Location L
inner join Payment P on L.LocationID = P.LocationID
group by L.LocationName
having sum(P.Amount) <500

--19  Calculate Total Payments per Location  
select L.LocationName , sum(P.Amount) as TotalPayments
from Location L
inner join Payment P on L.LocationID= P.LocationID
group by L.LocationName

--20 Retrieve couriers who have received payments totaling more than $1000 in a specific location 
--(LocationID = X):  
select C.SenderName as CourierName, sum(P.Amount) as TotalPayment
From Courier c
Inner join Payment P on C.CourierID= P.CourierID
where P.LocationID in (1,3,5)
group by C.SenderName
having sum(P.Amount) >=100

--21  Retrieve couriers who have received payments totaling more than $1000 after a certain date 
--(PaymentDate > 'YYYY-MM-DD'):
SELECT C.SenderName, SUM(P.Amount) AS TotalPayment
FROM Courier C
INNER JOIN Payment P ON C.CourierID = P.CourierID
WHERE P.PaymentDate > '2025-01-01' 
GROUP BY C.SenderName
HAVING SUM(P.Amount) > 100;

--22 . Retrieve locations where the total amount received is more than $5000 before a certain date 
 --(PaymentDate > 'YYYY-MM-DD')

 SELECT L.LocationName, SUM(P.Amount) AS TotalAmount
FROM Location L
INNER JOIN Payment P ON L.LocationID = P.LocationID
WHERE P.PaymentDate < '2025-04-01' 
GROUP BY L.LocationName
HAVING SUM(P.Amount) > 100;










